### ISSUE TITLE
High rate limit intended?

### ISSUE THREAD

**Issue by exokortex** [KaindorfCTF/ctfd-usertoken#1]
Really nice to have a rate limit, but is 10 requests every 5 seconds not a bit high?

https://github.com/KaindorfCTF/ctfd-usertoken/blob/9f334655042899d882ae6c45341471fc1b3570e3/usertoken.py#L27

**Comment by h4ckd0tm3** [comment]
I have no fucking idea why the rate limit is what it is.
It's been some time since I did that ^^'

Just make a pull request if you want it changed :)
